export default {
      appName: "Some App",
      menu: "مستر تاكو",
      menu_description: "متخصصون في التاكو على الطریقة الاسبنایة، تفضلو حیاكم االله شیكو على",
      city: "Example City",
      menu_section1: "armenu_section1",
      menu_section2: "armenu_section2",
      menu_section3: "armenu_section3",
      menu_section4: "armenu_section4",
      menu_section5: "armenu_section5",
      menu_section6: "armenu_section6",
      dish1: "Example Dish1",
      dish2: "Example Dish2",
      dish3: "Example Dish3",
      dish4: "Example Dish4",
      dish5: "Example Dish5",
      dish6: "Example Dish6",
      dish7: "Example Dish7",
      dish8: "Example Dish8",
      dish9: "Example Dish9",
      dish10: "Example Dish10",
      dish11: "Example Dish11",

      dish_descr: "lorem ipsum dolor sit amet",
    }
